video: Werror: fix [-Werror=duplicate-decl-specifier] warning
removed unused mdss_panel2str function.

Error message:
drivers/video/fbdev/qti/mdss_panel.h:39:20: error: duplicate 'const'
declaration specifier [-Werror=duplicate-decl-specifier]
  static const char const *names[] = {
	                      ^~~~~

Signed-off-by: Balaji Prakash J <bjagadee@codeaurora.org>
Change-Id: Ia08ac1ac15a1374e77be9e1f48db61dd3dc991b1