mmc: sdhci-msm: Werror: fix [-Werror=unused-function] warning
removed unused function.

Error message:
error: 'sdhci_msm_initialize_ice' defined but not used [-Werror=unused-function]
static int sdhci_msm_initialize_ice(struct sdhci_msm_host *msm_host,
            ^~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Balaji Prakash J <bjagadee@codeaurora.org>
Change-Id: I1c9264edf1ebb2ec9700d2213874d70d81b790fa