mtd: Werror: fix [-Werror=unused-label] warning
since the place where the label is referred is enclosed within
CONFIG_MTD_SUPPORTS_NVMEM config, enclosed the label also
within the config.

Error message:
error: label 'fail_nvmem_add' defined but not used [-Werror=unused-label]
 fail_nvmem_add:
  ^~~~~~~~~~~~~~

Signed-off-by: Balaji Prakash J <bjagadee@codeaurora.org>
Change-Id: Ib567642f2ce39c1a44a7fe5d1b2d12f5e60c68d7